sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t thatodikobo/react-test -f ./clients/Dockerfile.dev ./clients

script:
  - docker run -e CI=true thatodikobo/react-test npm test

after_success:
  - docker build -t thatodikobo/multi-clients ./clients
  - docker build -t thatodikobo/multi-nginx ./nginx
  - docker build -t thatodikobo/multi-server ./server
  - docker build -t thatodikobo/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push thatodikobo/multi-clients
  - docker push thatodikobo/multi-nginx
  - docker push thatodikobo/multi-server
  - docker push thatodikobo/multi-worker
